#### shares.yaml
# host: share

#### config.yaml
# backup path: default
# database at: default

## backup root path
backup path: \\readyshare\BACKUP\BACKUP\

## database should be located in backup path if you want to be able to cahnge which computer this runs from
database at: \\readyshare\BACKUP\BACKUP\database.csv

## this allows for avoiding backup of the exact same file no matter where its located.
allow duplicates: False


# unimplemented
## now you can move things around in the backup folders without creating duplicates
#keep latest: True  # works this way by default, no need to code other functionality.
#remove empty folders: True  # just use `parrot prune` from cli for this.
