#host: shared_folder
TV: Backup
MINI: LinuxBackup
BLUE: Backup
SHERA: Backup
SILVER: Backup
NEUREAL: Backup
W000010974: Backup
# backup can be implied
#//W000010974/Users/jmiller/Documents/share: work
#//silver/Users/jmiller: silver
#//jm-tv/Users/jmiller: tv
